// Pseudocode for each sorting algorithm

export const pseudocodes = {
  bubbleSort: [
    'function bubbleSort(array)',
    'for i = 0 to n-2',
    'for j = 0 to n-i-2',
    'if array[j] > array[j+1]',
    'swap(array[j], array[j+1])',
    'array[n-i-1] is now sorted',
  ],
  quickSort: [
    'function quickSort(array, low, high)',
    'if low < high',
    'partition and compare with pivot',
    'swap if needed',
    'recursively sort partitions',
  ],
  mergeSort: [
    'function mergeSort(array, left, right)',
    'if left < right',
    'find middle point',
    'compare left and right halves',
    'merge sorted subarrays',
  ],
  heapSort: [
    'function heapSort(array)',
    'build max heap',
    'compare parent and children',
    'swap to maintain heap property',
    'extract elements from heap',
  ],
  selectionSort: [
    'function selectionSort(array)',
    'for i = 0 to n-2',
    'find minimum element in unsorted part',
    'swap with first unsorted element',
    'element i is now sorted',
  ],
  insertionSort: [
    'function insertionSort(array)',
    'for i = 1 to n-1',
    'key = array[i]',
    'shift larger elements right',
    'insert key in correct position',
    'elements 0 to i are sorted',
  ],
  shellSort: [
    'function shellSort(array)',
    'gap = n/2, reduce gap by half each time',
    'for each gap size',
    'perform insertion sort on elements gap apart',
    'reduce gap until gap = 1',
  ],
  countingSort: [
    'function countingSort(array)',
    'find min and max values',
    'create count array of size (max-min+1)',
    'count frequency of each element',
    'calculate cumulative counts',
    'build output array using counts',
    'copy output back to original array',
  ],
  radixSort: [
    'function radixSort(array)',
    'find maximum number to determine digits',
    'for each digit place (1s, 10s, 100s, etc.)',
    'use counting sort on current digit',
    'array becomes sorted by current digit',
  ],
  bucketSort: [
    'function bucketSort(array)',
    'determine number of buckets',
    'distribute elements into buckets',
    'sort each bucket individually',
    'concatenate sorted buckets',
  ],
  timsort: [
    'function timsort(array)',
    'divide array into small runs (size 32-64)',
    'sort each run with insertion sort',
    'merge runs using merge sort',
    'use binary insertion for small arrays',
    'adaptive merging for efficiency',
  ],
  introsort: [
    'function introsort(array)',
    'use quicksort with depth limit',
    'switch to heapsort if depth exceeded',
    'use insertion sort for small subarrays',
    'combine best of all three algorithms',
  ],
};

export const algorithms = {
  bubbleSort: { name: 'Bubble Sort', pseudocode: pseudocodes.bubbleSort },
  selectionSort: { name: 'Selection Sort', pseudocode: pseudocodes.selectionSort },
  insertionSort: { name: 'Insertion Sort', pseudocode: pseudocodes.insertionSort },
  quickSort: { name: 'Quick Sort', pseudocode: pseudocodes.quickSort },
  mergeSort: { name: 'Merge Sort', pseudocode: pseudocodes.mergeSort },
  heapSort: { name: 'Heap Sort', pseudocode: pseudocodes.heapSort },
  shellSort: { name: 'Shell Sort', pseudocode: pseudocodes.shellSort },
  countingSort: { name: 'Counting Sort', pseudocode: pseudocodes.countingSort },
  radixSort: { name: 'Radix Sort', pseudocode: pseudocodes.radixSort },
  bucketSort: { name: 'Bucket Sort', pseudocode: pseudocodes.bucketSort },
  timsort: { name: 'Timsort', pseudocode: pseudocodes.timsort },
  introsort: { name: 'Introsort', pseudocode: pseudocodes.introsort },
};
